name: BuildingImageAndDeploying

# on:
#   release:
#     types: [prereleased,released]
on:
  push:
#    tags:
##    # types: [prereleased,released]

jobs:
  building:
    name: building
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push ${{ steps.get_version.outputs.VERSION }}
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.Production
          context: .
          push: true
#          aliabdalla/elirp:${{ steps.get_version.outputs.VERSION }},
          tags: aliabdalla/elirp:latest
  deploying:
    needs: building
    name: deploying
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: ssh to cluster
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MASTER_K8S_IP }}
          username: ${{ secrets.MASTER_K8S_USERNAME }}
          key: ${{ secrets.MASTER_K8S_PRIVATE_KEY }}
          fingerprint: ${{ secrets.MASTER_K8S_PUBLIC_KEY_FINGERPRINT }}
          script: |
            ${{ secrets.MASTER_K8S_READYNESS_SCRIPT }}
            cd ~/elirp-chart
            helm dependency update
            sed -i "s/^version:.*$/version: ${{ github.run_number }}/" Chart.yaml
            sed -i "s/^appVersion:.*$/appVersion: ${{ github.run_number }}/" Chart.yaml
            helm upgrade --install elirp  --version=${{ github.run_number }} -f values.yaml . --set image.tag=latest
